xmpp_jid: bot@example.net 
xmpp_password: hackme123
mumble_server: mumble.example.net 
mumble_port: 64738
polling_rate: 5 # delay in seconds
subscribers: # subscriber jids
  - person@example.net
  - john.doe@example.net
